/** Expanded Chapter 5 text content and table data */

module.exports = {
  intro: [
    'This chapter describes the practical implementation, deployment, and testing of the EyeCare (Al-Ixsaan) Management System. It explains the development environment, tools and technologies used, system setup procedures, operational workflows for each user role, the major software modules that were coded, and the comprehensive testing strategy adopted to validate the system against the requirements defined in Chapter Four.',
    'The EyeCare system is a web-based ophthalmology clinic management platform developed using a three-tier architecture: a Next.js frontend (presentation layer), a Node.js/Express REST API (application layer), and a PostgreSQL relational database managed through Prisma ORM (data layer). Real-time notifications are delivered using Socket.io. The system supports six user roles — Super Admin, Administrator, Doctor, Receptionist, Pharmacist, and Optician — each with role-based access control (RBAC) and granular module permissions.',
    'Implementation followed an iterative development approach where each module was built, tested, and integrated incrementally. Particular attention was paid to ensuring correct role separation as defined in the use case diagram: the Receptionist handles patient registration, appointment scheduling, and billing; the Doctor conducts examinations and manages prescriptions but does not schedule appointments; the Pharmacist and Optician handle dispensing workflows linked to billing.',
  ],

  implTools: [
    ['Next.js 16', 'Frontend web application framework with App Router'],
    ['React 19', 'Component-based user interface library'],
    ['TypeScript 5', 'Type-safe frontend development'],
    ['Tailwind CSS 4', 'Utility-first responsive styling'],
    ['Node.js 18+', 'JavaScript runtime for backend server'],
    ['Express.js 5', 'REST API framework and middleware'],
    ['Prisma ORM 6.4', 'Database schema, migrations, and queries'],
    ['PostgreSQL 14+', 'Relational database management system'],
    ['JWT (jsonwebtoken)', 'Authentication token generation and verification'],
    ['bcrypt', 'Secure one-way password hashing'],
    ['Joi 18', 'Request body and input validation'],
    ['Socket.io 4.8', 'Real-time bidirectional notifications'],
    ['Axios', 'HTTP client for frontend API communication'],
    ['Recharts 3.7', 'Dashboard charts and analytics visualisation'],
    ['jsPDF 2.5', 'PDF export for reports, invoices, and receipts'],
    ['Nodemailer 8', 'Email delivery for password reset'],
    ['Multer 2', 'Profile image and file upload handling'],
    ['Visual Studio Code', 'Primary integrated development environment'],
    ['Git', 'Version control and collaborative development'],
    ['Playwright', 'Automated browser testing and screenshot capture'],
  ],

  hardware: [
    ['1', 'Development Computer', '1–4 units', 'Intel Core i5 or equivalent, 8 GB RAM minimum, 256 GB SSD, Windows 10/11'],
    ['2', 'Database Server', '1 unit', '4 GB RAM minimum, SSD storage, PostgreSQL 14+ installed'],
    ['3', 'Application Server', '1 unit', '4 GB RAM, Node.js 18+, for hosting Express API'],
    ['4', 'Network', '1', 'Stable broadband connection for development and deployment'],
    ['5', 'Client Devices', '2+', 'Desktop or laptop with modern browser (Chrome, Edge, Firefox)'],
  ],

  software: [
    ['1', 'Operating System', 'Windows 10/11, Linux, or macOS'],
    ['2', 'Node.js & npm', 'Runtime and package manager for frontend and backend'],
    ['3', 'PostgreSQL', 'Database server with DATABASE_URL configured in .env'],
    ['4', 'Web Browser', 'Chrome or Edge (latest) for UI testing and demonstration'],
    ['5', 'Environment Variables', 'DATABASE_URL, JWT_SECRET, optional SMTP for email'],
  ],

  setupSteps: [
    ['Project Initialization', 'The project was initialized with a monorepo structure containing a Next.js frontend (frontend/) and Node.js/Express backend (backend/). Modules were organised for authentication, patients, appointments, eye examinations, prescriptions, pharmacy inventory, optical shop, billing, administration, reports, and audit logging.'],
    ['Database Configuration', 'PostgreSQL was configured as the primary data store. The Prisma schema (backend/prisma/schema.prisma) defines all entities, relationships, and constraints. Migrations were applied using npx prisma migrate deploy to create tables with UUID primary keys and branch-scoped foreign keys.'],
    ['Authentication Integration', 'JWT-based authentication was implemented in authController.js with bcrypt password hashing. The authenticate middleware validates tokens on every protected route. Roles assigned at registration: SUPERADMIN, ADMIN, DOCTOR, RECEPTIONIST, PHARMACIST, OPTICIAN.'],
    ['Database Seeding', 'Initial seed data was created using backend/seed.js — default branch, demo users per role, doctor profiles, sample patients, and role permissions. This enabled immediate end-to-end testing after deployment.'],
    ['UI Design and Routing', 'The Next.js App Router organises pages under frontend/src/app/dashboard/. Each role receives a tailored sidebar navigation filtered by permissions. Forms use reusable UI components from Radix UI and Tailwind CSS with light-mode-first styling.'],
    ['API Route Mounting', 'All 22 route files were mounted in server.js under /api/* prefixes. Error handling middleware returns consistent JSON responses. CORS is enabled for local development. Socket.io is initialised for real-time notification delivery.'],
    ['Testing and Debugging', 'Unit, integration, system, and user acceptance testing were performed. Postman and browser DevTools were used for API testing. Playwright was used for automated screenshot capture and UI verification.'],
  ],

  operations: [
    ['Receptionist', 'The Receptionist is the front-desk operator of the clinic. After logging in, the Receptionist registers new patients with full name, phone, gender, date of birth, and address. The Receptionist schedules appointments by selecting a patient, doctor, date, and time slot — this is exclusively a Receptionist function, not a Doctor function. The Receptionist also generates billing invoices for consultations, pharmacy sales, and optical products, and records payment status. The appointment calendar provides a daily and weekly view of all scheduled visits.'],
    ['Doctor', 'The Doctor logs in to view a personalised dashboard showing today\'s appointments and patient queue. The Doctor conducts preliminary examinations (visual acuity, intraocular pressure) and clinical examinations (detailed findings, diagnosis). The Doctor creates medicine prescriptions (drug, dosage, frequency, duration) and optical prescriptions (refraction values, lens recommendations). The Doctor does not register patients, schedule appointments, or handle billing — these remain Receptionist responsibilities as per the use case diagram.'],
    ['Pharmacist', 'The Pharmacist views medicine prescriptions created by doctors and manages pharmacy inventory including stock levels, purchase records, and dispensing transactions. When dispensing medicine, stock is automatically decremented and the dispensing action is linked to the billing module. Low-stock alerts are pushed in real time via Socket.io to the pharmacist dashboard.'],
    ['Optician', 'The Optician views optical prescriptions, manages the frame and lens inventory, and creates optical shop orders. Dispensing optical products follows the same billing integration as pharmacy dispensing. The Optician can view prescription details including sphere, cylinder, axis, and recommended lens type.'],
    ['Administrator', 'The Administrator manages clinic staff by creating and updating user accounts, assigning roles, and maintaining doctor profiles with license numbers and specializations. The Administrator accesses operational and financial reports including appointment analytics, patient statistics, revenue trends, and doctor performance metrics.'],
    ['Super Admin', 'The Super Admin has system-wide access across all branches. Responsibilities include creating and managing clinic branches, configuring granular role permissions per module (canRead, canCreate, canUpdate, canDelete), and reviewing activity logs and audit trails. The Super Admin can switch between branches using the branch selector.'],
    ['Data Synchronisation', 'All user actions are persisted to PostgreSQL through REST API calls. Profile images are uploaded via Multer and served from /uploads. Socket.io pushes real-time notifications for new appointments, low inventory, and billing events. Changes made by one role are immediately visible to other authorised roles on the same branch.'],
  ],

  modules: [
    ['Authentication', '/api/auth', 'authController.js', 'Login, logout, password reset, JWT issuance, bcrypt hashing'],
    ['Users', '/api/users', 'userController.js', 'CRUD for staff accounts, profile management, role assignment'],
    ['Branches', '/api/branches', 'branchController.js', 'Multi-branch clinic setup — Super Admin and Admin only'],
    ['Patients', '/api/patients', 'patientController.js', 'Registration, search, profile, medical history — Receptionist primary'],
    ['Appointments', '/api/appointments', 'appointmentController.js', 'Schedule, reschedule, cancel, calendar — Receptionist only'],
    ['Eye Examinations', '/api/eye-examinations', 'eyeExaminationController.js', 'Preliminary and clinical exams — Doctor'],
    ['Doctors', '/api/doctors', 'doctorController.js', 'Doctor profiles, specialization, license numbers'],
    ['Medicine Prescriptions', '/api/prescription-items', 'medicinePrescriptionController.js', 'Drug prescriptions — Doctor creates, Pharmacist dispenses'],
    ['Optical Prescriptions', '/api/prescriptions', 'opticalPrescriptionController.js', 'Refraction and lens Rx — Doctor creates, Optician fulfills'],
    ['Pharmacy Inventory', '/api/inventory/pharmacy', 'pharmacyItemController.js', 'Stock, purchases, transactions, dispensing'],
    ['Optical Inventory', '/api/inventory/optical', 'opticalItemController.js', 'Frames, lenses, stock transactions, orders'],
    ['Billing', '/api/billing', 'billingController.js', 'Invoices, payments, receipts — Receptionist'],
    ['Reports', '/api/reports', 'reportController.js', 'Clinical, financial, operational, appointment analytics'],
    ['Permissions', '/api/permissions', 'permissionController.js', 'Granular RBAC per module and action'],
    ['Activity Logs', '/api/activity-logs', 'activityLogController.js', 'User action tracking with IP and timestamp'],
    ['Audit Logs', '/api/audit-logs', 'auditLogController.js', 'Before/after value capture for sensitive changes'],
    ['Notifications', '/api/notifications', 'notificationController.js', 'Real-time alerts via Socket.io'],
    ['Dashboard', '/api/dashboard', 'dashboardController.js', 'Role-specific KPIs and summary statistics'],
  ],

  apiEndpoints: [
    ['POST', '/api/auth/login', 'Authenticate user and return JWT'],
    ['GET', '/api/patients', 'List patients for current branch'],
    ['POST', '/api/patients', 'Register new patient'],
    ['GET', '/api/appointments', 'List appointments with filters'],
    ['POST', '/api/appointments', 'Schedule new appointment'],
    ['GET', '/api/eye-examinations', 'List examination records'],
    ['POST', '/api/eye-examinations', 'Create examination record'],
    ['POST', '/api/prescription-items', 'Create medicine prescription'],
    ['POST', '/api/prescriptions', 'Create optical prescription'],
    ['GET', '/api/inventory/pharmacy', 'List pharmacy stock'],
    ['POST', '/api/billing', 'Create billing invoice'],
    ['GET', '/api/reports/clinical', 'Generate clinical report'],
    ['GET', '/api/reports/financial', 'Generate financial report'],
    ['PUT', '/api/permissions/:role', 'Update role permissions'],
    ['GET', '/api/activity-logs', 'Retrieve activity log entries'],
    ['GET', '/api/audit-logs', 'Retrieve audit trail entries'],
  ],

  dbTables: [
    ['clinic_branch', 'Branch', 'Clinic locations with name, address, phone'],
    ['users', 'User', 'Staff accounts with role, branch, credentials'],
    ['patients', 'Patient', 'Patient demographics and contact details'],
    ['appointments', 'Appointment', 'Scheduled visits linking patient and doctor'],
    ['eye_examinations', 'EyeExamination', 'Preliminary and clinical exam records'],
    ['prescriptions', 'Prescription', 'Medicine prescriptions'],
    ['optical_prescriptions', 'OpticalPrescription', 'Optical/refraction prescriptions'],
    ['pharmacy_items', 'PharmacyItem', 'Pharmacy inventory stock items'],
    ['optical_items', 'OpticalItem', 'Frames and lenses inventory'],
    ['billing', 'Billing', 'Invoices and payment records'],
    ['activity_logs', 'ActivityLog', 'User action audit entries'],
    ['audit_logs', 'AuditLog', 'Change tracking with old/new values'],
    ['role_permissions', 'RolePermission', 'Granular module access per role'],
  ],

  unitTests: [
    ['Login form — valid credentials', 'Form submits; JWT returned', 'Pass'],
    ['Login form — empty username', 'Validation error shown', 'Pass'],
    ['Login form — wrong password', 'Error message displayed', 'Pass'],
    ['Patient form — missing name', 'Joi validation rejects request', 'Pass'],
    ['Patient form — valid data', 'Patient created in database', 'Pass'],
    ['Appointment form — past date', 'Validation error returned', 'Pass'],
    ['Billing form — negative amount', 'Validation error returned', 'Pass'],
    ['Password hashing', 'bcrypt hash stored, not plain text', 'Pass'],
  ],

  integrationTests: [
    ['Auth → Protected route', 'JWT middleware blocks unauthenticated access', 'Pass'],
    ['Patient → Appointment', 'Registered patient appears in appointment selector', 'Pass'],
    ['Appointment → Examination', 'Examination linked to appointment record', 'Pass'],
    ['Prescription → Pharmacy', 'Medicine Rx visible in pharmacy module', 'Pass'],
    ['Dispense → Billing', 'Dispensing triggers billing line item', 'Pass'],
    ['Role → Sidebar', 'Menu items match role permissions', 'Pass'],
    ['Socket.io → Dashboard', 'Low-stock alert received in real time', 'Pass'],
    ['Branch header → Data scope', 'API returns only current branch data', 'Pass'],
  ],

  uatParticipants: [
    ['Receptionist', 'Clinic front desk staff', 'Patient registration speed, calendar usability', 'Positive — workflow intuitive'],
    ['Doctor', 'Ophthalmologist', 'Examination form completeness, prescription flow', 'Positive — all fields present'],
    ['Pharmacist', 'Pharmacy staff', 'Inventory lookup, dispensing accuracy', 'Positive — stock updates correctly'],
    ['Administrator', 'Clinic manager', 'Report readability, user management', 'Positive — reports informative'],
    ['Super Admin', 'IT administrator', 'Permission configuration, audit logs', 'Positive — granular control works'],
  ],

  testCases: [
    ['User login with valid credentials', 'JWT issued; redirect to role dashboard', 'Pass'],
    ['Login with wrong password', 'Error message; access denied', 'Pass'],
    ['Access API without token', 'HTTP 401 Unauthorized', 'Pass'],
    ['Receptionist registers patient', 'Patient saved with UUID', 'Pass'],
    ['Receptionist schedules appointment', 'Appointment status SCHEDULED', 'Pass'],
    ['Doctor tries to schedule appointment', 'Access denied — Receptionist only', 'Pass'],
    ['Doctor conducts examination', 'Record linked to patient', 'Pass'],
    ['Doctor creates medicine prescription', 'Visible to pharmacist', 'Pass'],
    ['Doctor creates optical prescription', 'Visible to optician', 'Pass'],
    ['Pharmacist dispenses medicine', 'Stock reduced; transaction logged', 'Pass'],
    ['Dispense with insufficient stock', 'Error: insufficient stock', 'Pass'],
    ['Optician dispenses optical product', 'Order saved; stock updated', 'Pass'],
    ['Receptionist creates bill', 'Invoice with correct total', 'Pass'],
    ['Doctor accesses admin panel', 'HTTP 403; menu hidden', 'Pass'],
    ['Super Admin updates permissions', 'Change applied immediately', 'Pass'],
    ['Low stock notification', 'Socket.io alert on dashboard', 'Pass'],
    ['Multi-branch data isolation', 'Branch-scoped query results', 'Pass'],
    ['Activity log on patient create', 'Log entry with user and timestamp', 'Pass'],
    ['Audit log on role change', 'Old and new values captured', 'Pass'],
    ['Generate financial report', 'Filtered revenue data displayed', 'Pass'],
  ],

  useCaseValidation: [
    ['Receptionist', 'Register Patient', 'Pass'],
    ['Receptionist', 'Schedule Appointment', 'Pass'],
    ['Receptionist', 'Billing', 'Pass'],
    ['Doctor', 'View Dashboard', 'Pass'],
    ['Doctor', 'Conduct Examination', 'Pass'],
    ['Doctor', 'Manage Prescriptions', 'Pass'],
    ['Pharmacist', 'Dispense Medicine', 'Pass'],
    ['Pharmacist', 'Manage Pharmacy Inventory', 'Pass'],
    ['Pharmacist', 'Pharmacy Sales', 'Pass'],
    ['Optician', 'View Prescription', 'Pass'],
    ['Optician', 'Manage Optical Inventory', 'Pass'],
    ['Optician', 'Dispense Optical Products', 'Pass'],
    ['Administrator', 'Manage Users', 'Pass'],
    ['Administrator', 'Manage Doctors', 'Pass'],
    ['Administrator', 'View Reports', 'Pass'],
    ['Super Admin', 'Manage Branches', 'Pass'],
    ['Super Admin', 'Manage Role Permissions', 'Pass'],
    ['Super Admin', 'Activity & Audit Logs', 'Pass'],
  ],

  securityMeasures: [
    ['Authentication required', 'JWT middleware on all protected routes', 'Verified'],
    ['Password hashing', 'bcrypt with salt rounds — no plain text storage', 'Verified'],
    ['Role-based access', 'authorize() middleware per route', 'Verified'],
    ['Permission granularity', 'checkPermission() per module action', 'Verified'],
    ['Branch isolation', 'branchId filter on queries', 'Verified'],
    ['Input validation', 'Joi schemas reject malformed data', 'Verified'],
    ['SQL injection prevention', 'Prisma parameterized queries', 'Verified'],
    ['Activity logging', 'All CRUD operations logged', 'Verified'],
    ['Audit trail', 'Sensitive changes capture old/new values', 'Verified'],
  ],

  challenges: [
    ['Multi-branch data scoping', 'Implemented branchId filter in all controllers and x-branch-id header support for Super Admin branch switching.'],
    ['Role permission granularity', 'Created role_permissions table with canRead, canCreate, canUpdate, canDelete per module, enforced via checkPermission middleware.'],
    ['Prescription workflow separation', 'Split medicine prescriptions (/api/prescription-items) and optical prescriptions (/api/prescriptions) into separate modules with distinct Prisma models.'],
    ['Real-time notifications', 'Integrated Socket.io on both server and client; notification controller aggregates alerts per role.'],
    ['Billing integration', 'Linked pharmacy and optical dispensing to billing module so dispense actions automatically include billing as per use case <<include>> relationship.'],
  ],

  summary: [
    'The EyeCare (Al-Ixsaan) Management System was successfully implemented using Next.js, Node.js/Express, Prisma ORM, and PostgreSQL following a three-tier architecture. Eighteen major modules were developed covering the complete ophthalmology clinic workflow from patient registration through examination, prescription, dispensing, billing, and reporting.',
    'System testing at four levels — unit, integration, system, and user acceptance — confirmed that all functional and non-functional requirements from Chapter Four were met. Twenty test cases were executed with a 100% pass rate. Role separation was verified: the Receptionist handles registration, scheduling, and billing; the Doctor handles examinations and prescriptions only.',
    'Security measures including JWT authentication, bcrypt password hashing, role-based access control, branch data isolation, and comprehensive activity/audit logging were implemented and verified. The system is ready for deployment in a live clinic environment. Chapter Six presents the results, evaluation metrics, comparison with existing systems, and discussion of findings.',
  ],
};
