/**
 * Thesis metadata — edit names, IDs, and supervisor before generating preface.
 */
module.exports = {
  university: 'Jazeera University',
  faculty: 'Faculty of Computer Science and Information Technology',
  degree: 'Bachelor of Computer Science and Information Technology',
  projectTitle: 'EyeCare (Al-Ixsaan) Management System',
  projectSubtitle:
    'Design and Implementation of an Integrated Web-Based Ophthalmology Clinic Management System',
  fieldOfStudy: 'Web Application Development',
  submissionDate: 'June, 2026',
  supervisor: 'Eng. Abdisalan Abdullahi Mohamed',
  researchCoordinator: 'Eng. _________________________',
  dean: 'Eng. Jamila Hassan Mohamed',

  // Add or remove candidates for your group
  candidates: [
    { name: 'Yonis Khalif Abdulle', id: 'CS1300721' },
    { name: 'Sahra Mohamed Hussein', id: 'CS1300712' },
    { name: 'Abdikafi Dahir Samatar', id: 'CS1300734' },
    { name: 'Faiza Abdirahman Said', id: 'CS1300684' },
    { name: 'Omar Mohamud Mahdi', id: 'CS1300709' },
  ],

  abstract: `This project proposes the design and implementation of a comprehensive EyeCare (Al-Ixsaan) Management System aimed at addressing the major challenges posed by manual documentation in ophthalmology clinics and eye care centers. Traditional paper-based records are often prone to errors, misplacement, and delays in information retrieval, which negatively affect service delivery, clinical decision-making, and administrative coordination. To bridge these gaps, the proposed system integrates key ophthalmology clinic services—including patient registration, appointment scheduling, clinical examinations, prescription management, pharmacy dispensing, optical services, billing, and reporting—into a unified electronic platform tailored for Al-Ixsaan Medical Group and similar facilities.

The system was developed using Next.js, React, TypeScript, Node.js, Express, PostgreSQL, and Prisma ORM technologies, ensuring secure data storage, role-based access control, and real-time validation of clinical and administrative information. Six user roles were implemented—Super Admin, Administrator, Doctor, Receptionist, Pharmacist, and Optician—each with clearly defined permissions that reflect real clinic workflows. These features significantly reduce errors in patient management, prevent scheduling conflicts, and improve data accuracy across reception, clinical, pharmacy, and billing departments.

Moreover, the platform incorporates modules for visual acuity recording, intraocular pressure monitoring, electronic prescribing, inventory tracking, automated report generation, and activity auditing, which collectively enhance decision-making and service efficiency. Testing and evaluation of the system demonstrated increased efficiency, accuracy, and usability across various clinic workflows. Healthcare providers benefited from faster data entry, easier access to patient histories, and improved coordination between departmental staff. In addition, the system provides valuable insights through timely reports that support resource allocation, operational planning, and long-term management of ophthalmology services.`,

  acknowledgements: `First and foremost, all praise is due to Almighty Allah, who granted us the strength, wisdom, and opportunity to accomplish this work successfully.

We express our heartfelt gratitude to our supervisor, Eng. Abdisalan Abdullahi Mohamed, for his valuable guidance, continuous support, and constructive corrections from the proposal stage to the completion of this thesis.

We extend our appreciation to our parents and families for their endless love, encouragement, and prayers throughout our academic journey at Jazeera University.

Special thanks go to the lecturers and staff of the Faculty of Computer Science and Information Technology for sharing their expertise and providing the knowledge needed to complete this degree.

We also thank the Al-Ixsaan Medical Group team and clinic staff who provided practical insights into ophthalmology clinic workflows, which informed the system requirements and use case design.

Finally, we thank our classmates and colleagues for their cooperation and encouragement during this Final Year Project.`,

  figures: [
    ['Figure 3.1', 'Operational Framework / System Development Environment'],
    ['Figure 3.2', 'Use Case Diagram — EyeCare Management System'],
    ['Figure 3.3', 'DFD Level 0 — Context Diagram'],
    ['Figure 3.4', 'DFD Level 1 — Process Decomposition'],
    ['Figure 3.5', 'Entity Relationship Diagram (ERD)'],
    ['Figure 4.1', 'System Architecture Diagram'],
    ['Figure 4.2', 'Login Screen'],
    ['Figure 4.3', 'Receptionist Dashboard'],
    ['Figure 4.4', 'Patient Registration Interface'],
    ['Figure 4.5', 'Appointment Scheduling Calendar'],
    ['Figure 4.6', 'Clinical Examination Form'],
    ['Figure 4.7', 'Prescription Management Interface'],
    ['Figure 4.8', 'Pharmacy Inventory Screen'],
    ['Figure 4.9', 'Billing Interface'],
    ['Figure 4.10', 'Reports Dashboard'],
    ['Figure 5.1', 'Three-Tier System Architecture'],
    ['Figure 5.2', 'Receptionist Dashboard — Light Mode'],
    ['Figure 5.3', 'Doctor Dashboard — Light Mode'],
    ['Figure 5.4', 'Role Permission Configuration'],
    ['Figure 5.5', 'Unit Testing — Login, Patient, Appointment'],
    ['Figure 5.6', 'Integration Testing Flow'],
    ['Figure 5.7', 'Clinic Workflow — End-to-End Testing'],
    ['Figure 5.8', 'System Testing — Full Workflow Screenshots'],
    ['Figure 5.9', 'User Acceptance Testing Process'],
    ['Figure 5.10', 'Validation and Verification Flow'],
    ['Figure 5.11', 'Activity and Audit Log Viewer'],
    ['Figure 6.1', 'Testing Pass Rate by Category'],
    ['Figure 6.2', 'UAT Satisfaction Ratings by Role'],
    ['Figure 6.3', 'Receptionist Dashboard — Results'],
    ['Figure 6.4', 'Clinical Examination Module'],
    ['Figure 6.5', 'Billing Module'],
    ['Figure 6.6', 'Reports Module'],
    ['Figure 6.7', 'System Capability Comparison'],
    ['Figure 6.8', 'Evaluation Metrics Summary'],
  ],

  tables: [
    ['Table 3.1', 'Software Requirements'],
    ['Table 3.2', 'Hardware Requirements'],
    ['Table 3.3', 'Project Timeline'],
    ['Table 4.1', 'Functional Requirements'],
    ['Table 4.2', 'Non-Functional Requirements'],
    ['Table 4.3', 'Database Tables Description'],
    ['Table 5.1', 'Implementation Tools'],
    ['Table 5.2', 'Hardware Requirements'],
    ['Table 5.3', 'Software Requirements'],
    ['Table 5.4', 'System Modules'],
    ['Table 5.5', 'Representative API Endpoints'],
    ['Table 5.6', 'Database Tables'],
    ['Table 5.7', 'Unit Test Results'],
    ['Table 5.8', 'Integration Test Results'],
    ['Table 5.9', 'UAT Participants and Feedback'],
    ['Table 5.10', 'Testing Results'],
    ['Table 5.11', 'Use Case Validation'],
    ['Table 5.12', 'Security Measures Verification'],
    ['Table 5.13', 'Implementation Challenges and Solutions'],
    ['Table 6.1', 'Module Implementation Results'],
    ['Table 6.2', 'Testing Summary'],
    ['Table 6.3', 'UAT Satisfaction Ratings'],
    ['Table 6.4', 'System Performance Results'],
    ['Table 6.5', 'Role Workflow Verification'],
    ['Table 6.6', 'Stakeholder Benefits'],
    ['Table 6.7', 'Comparison with Existing Systems'],
    ['Table 6.8', 'System Limitations and Mitigations'],
    ['Table 6.9', 'Evaluation Metrics'],
    ['Table 7.1', 'Recommendations'],
    ['Table 7.2', 'Future Work'],
  ],

  abbreviations: [
    ['API', 'Application Programming Interface'],
    ['RBAC', 'Role-Based Access Control'],
    ['JWT', 'JSON Web Token'],
    ['ERD', 'Entity Relationship Diagram'],
    ['DFD', 'Data Flow Diagram'],
    ['UML', 'Unified Modeling Language'],
    ['UI', 'User Interface'],
    ['UX', 'User Experience'],
    ['DB', 'Database'],
    ['ORM', 'Object-Relational Mapping'],
    ['CRUD', 'Create, Read, Update, Delete'],
    ['HMS', 'Hospital Management System'],
    ['UAT', 'User Acceptance Testing'],
    ['SRS', 'Software Requirements Specification'],
    ['IOP', 'Intraocular Pressure'],
    ['VA', 'Visual Acuity'],
    ['OD', 'Oculus Dexter (Right Eye)'],
    ['OS', 'Oculus Sinister (Left Eye)'],
    ['OU', 'Oculus Uterque (Both Eyes)'],
    ['Rx', 'Prescription'],
    ['IDE', 'Integrated Development Environment'],
    ['REST', 'Representational State Transfer'],
    ['PDF', 'Portable Document Format'],
    ['ICT', 'Information and Communication Technology'],
    ['FYP', 'Final Year Project'],
    ['JU', 'Jazeera University'],
    ['CS/IT', 'Computer Science and Information Technology'],
  ],

  appendices: [
    ['Appendix A', 'Source Code — Key Module Listings (backend routes, controllers, Prisma schema)'],
    ['Appendix B', 'Additional Diagrams — Use Case Diagram, ERD, System Architecture'],
    ['Appendix C', 'Test Cases — Complete Testing Results from Chapter Five'],
    ['Appendix D', 'User Interface Screenshots — Role Dashboards and Module Screens'],
    ['Appendix E', 'Database Schema — Prisma Migration Scripts'],
    ['Appendix F', 'Installation and Deployment Guide'],
  ],

  toc: [
    { section: 'FRONT MATTER', page: '', bold: true },
    { section: 'Title Page', page: 'i' },
    { section: 'Original Literary Work Declaration', page: 'ii' },
    { section: 'Abstract', page: 'iii' },
    { section: 'Acknowledgements', page: 'iv' },
    { section: 'Table of Contents', page: 'v' },
    { section: 'List of Figures', page: 'vi' },
    { section: 'List of Tables', page: 'vii' },
    { section: 'List of Symbols and Abbreviations', page: 'viii' },
    { section: 'List of Appendices', page: 'ix' },
    { section: 'CHAPTER ONE: INTRODUCTION', page: '1', bold: true },
    { section: '1.0 Introduction', page: '1' },
    { section: '1.1 Background', page: '1' },
    { section: '1.2 Problem Statement', page: '2' },
    { section: '1.3 Research Objectives', page: '3' },
    { section: '1.4 Research Questions', page: '4' },
    { section: '1.5 Motivation of the Study', page: '4' },
    { section: '1.6 Significance of the Study', page: '5' },
    { section: '1.7 Scope of the Study', page: '6' },
    { section: '1.8 Organization of the Study', page: '6' },
    { section: '1.9 Key Terms', page: '7' },
    { section: 'CHAPTER TWO: LITERATURE REVIEW', page: '8', bold: true },
    { section: '2.0 Introduction', page: '8' },
    { section: '2.1 Theoretical Framework', page: '8' },
    { section: '2.2 Related Work', page: '10' },
    { section: '2.3 Critical Review & Gap Identification', page: '13' },
    { section: '2.4 Chapter Summary', page: '15' },
    { section: 'CHAPTER THREE: METHODOLOGY', page: '16', bold: true },
    { section: '3.0 Introduction', page: '16' },
    { section: '3.1 Research Design', page: '16' },
    { section: '3.2 System Description', page: '16' },
    { section: '3.3 Overview of the System', page: '17' },
    { section: '3.4 System Features', page: '17' },
    { section: '3.5 System Development Environment', page: '18' },
    { section: '3.6 System Requirement Specification', page: '18' },
    { section: '3.7 Chapter Summary', page: '26' },
    { section: 'CHAPTER FOUR: ANALYSIS AND DESIGN', page: '27', bold: true },
    { section: '4.0 Introduction', page: '27' },
    { section: '4.1 System Analysis', page: '27' },
    { section: '4.2 Existing Approaches', page: '28' },
    { section: '4.3 The Proposed System', page: '28' },
    { section: '4.4 Requirements', page: '28' },
    { section: '4.5 Feasibility Study', page: '30' },
    { section: '4.6 System Design', page: '31' },
    { section: '4.7 Database Design', page: '35' },
    { section: '4.8 System Architecture Diagram', page: '38' },
    { section: '4.9 Chapter Summary', page: '39' },
    { section: 'CHAPTER FIVE: IMPLEMENTATION & TESTING', page: '40', bold: true },
    { section: '5.0 Introduction', page: '40' },
    { section: '5.1 Implementation Tools and Environment', page: '40' },
    { section: '5.2 System Setup and Deployment Steps', page: '41' },
    { section: '5.3 System Operations', page: '42' },
    { section: '5.4 Coding and Modules', page: '44' },
    { section: '5.5 Testing Strategy', page: '46' },
    { section: '5.6 Test Cases and Results', page: '48' },
    { section: '5.7 Validation and Verification', page: '50' },
    { section: '5.8 Implementation Challenges', page: '52' },
    { section: '5.9 Chapter Summary', page: '53' },
    { section: 'CHAPTER SIX: RESULTS AND DISCUSSION', page: '54', bold: true },
    { section: '6.0 Introduction', page: '54' },
    { section: '6.1 Results Presentation', page: '54' },
    { section: '6.2 Research Questions — Answers', page: '58' },
    { section: '6.3 Research Objectives — Achievement', page: '62' },
    { section: '6.4 Key Outcomes', page: '65' },
    { section: '6.5 Comparison with Existing Systems', page: '66' },
    { section: '6.6 Limitations Identified', page: '68' },
    { section: '6.7 Evaluation Metrics', page: '69' },
    { section: '6.8 Discussion of Findings', page: '70' },
    { section: '6.9 Chapter Summary', page: '72' },
    { section: 'CHAPTER SEVEN: CONCLUSION & FUTURE WORK', page: '73', bold: true },
    { section: '7.0 Introduction', page: '73' },
    { section: '7.1 Summary of Key Findings', page: '73' },
    { section: '7.2 Conclusion', page: '74' },
    { section: '7.3 Recommendations', page: '75' },
    { section: '7.4 Future Work', page: '76' },
    { section: '7.5 Chapter Summary', page: '78' },
    { section: 'REFERENCES / BIBLIOGRAPHY', page: '79', bold: true },
    { section: 'APPENDICES', page: '81', bold: true },
  ],
};
